### PR TITLE
Change package name(#6)

### PR DESCRIPTION
**Pull request by yeonjiyeon**
I change package name from euphony_hub to euphony_hub_controller.

### CODE REVIEW

**Comment by designe** [comment]
Hi! @yeonjiyeon Thanks for trying to resolve `good-first-issue`
As you can see, there is some conflicts issue. 

```
<<<<<<< HEAD:app/src/main/java/co/jbear/euphony_hub/MainActivity.kt
import co.jbear.euphony_hub.data.repository.PreferenceRepository
import co.jbear.euphony_hub.ui.theme.EuphonyHubTheme
import co.jbear.euphony_hub.ui.view.Home
=======
import androidx.core.app.ActivityCompat
import co.jbear.euphony_hub_controller.data.repository.PreferenceRepository
import co.jbear.euphony_hub_controller.ui.theme.EuphonyHubTheme
import co.jbear.euphony_hub_controller.ui.view.Home
>>>>>>> cb42cb184dafb8fccc326935b206ab65f02cea6e:app/src/main/java/co/jbear/euphony_hub_controller/MainActivity.kt
```

is should be like below :)
```
import co.jbear.euphony_hub_controller.data.repository.PreferenceRepository
import co.jbear.euphony_hub_controller.ui.theme.EuphonyHubTheme
import co.jbear.euphony_hub_controller.ui.view.Home
```

please resolve the conflict :)

**Comment by designe** [comment]
+ not euphony-hub-controller, but `euphony-hub-collector`.

**Review by yeonns — COMMENTED** [review]
https://github.com/euphony-io/euphony-hub-collector/blob/1d3eec32d50927a89c7e9049221245e4c94c4b59/app/src/main/java/co/jbear/euphony_hub/ui/theme/Theme.kt#L31

```Theme``` file also should be modified.
Its function name should be changed from ```EuphonyHubTheme``` to ```EuphonyHubCollectorTheme```

**Comment by yeonjiyeon** [comment]
I fixed the conflict and reflected the part you mentioned and corrected it.

**Review by yeonns — COMMENTED** [review]
@yeonjiyeon 
```MainActivity``` is not the latest version. You should pull master branch of euphony-hub-collector and resolve your conflict.
```sh
$ git remote add euphony https://github.com/euphony-io/euphony-hub-collector
$ git pull euphony master
# pull result will occur conflict!
# you should resolve this conflict and make commit and push to your repository.
```

**Comment by yeonjiyeon** [comment]
Thanks for your help. But when I enter the command you gave me, it shows up as the latest version.
This is the log I got.
user@DESKTOP-5C0LL0S MINGW64 ~/OneDrive/문서/euphony-hub-collector (master)
$ git remote add euphony https://github.com/euphony-io/euphony-hub-collector

user@DESKTOP-5C0LL0S MINGW64 ~/OneDrive/문서/euphony-hub-collector (master)
$ git pull euphony master
From https://github.com/euphony-io/euphony-hub-collector
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> euphony/master
**Already up to date.**

**Comment by yeonns** [comment]
@yeonjiyeon Now, I found the the problem!
I think you should make another branch and cherry-pick your ```change package name``` commits!
Your commits related to #6 are like below:
(you can check commit history at [this link](https://github.com/yeonjiyeon/euphony-hub-collector/commits/master))
```
ce73265 refactor: change package name
1fd2652 refactor: change package name
```

So, how about closing this PR and make another one? Try this commands:
```sh
# make new branch for issue #6
$ git checkout -b refactor

# get latest version of master branch 
$ git reset --hard euphony/master

# cherry-pick your commits and merge to refactor branch
$ git cherry-pick 1fd2652
$ git cherry-pick ce73265
$ git push origin refactor

# Then, let's make PR from origin/refactor -> euphony/master
```

**Pull request closed without merging**
