### PR TITLE
Create question template 

### PR DESCRIPTION
**Pull request by nodobi**
Create question.yaml #14

###  References
 - https://github.com/IBMa/equal-access/blob/master/.github/ISSUE_TEMPLATE/question.yaml

### CODE REVIEW

**Review by yeonns — COMMENTED** [review]
@nodobi Thank you for creating question template!
I think it would be good to link this template to discussions like ```euphony```:
https://github.com/euphony-io/euphony/issues/new/choose

**Comment by nodobi** [comment]
@yeonns Thanks for your advice!
I understand that linking discussion is better than using question template.
Do I understand correctly?

**Comment by yeonns** [comment]
@nodobi yes right! :) So, you can add ```config.yml``` file like euphony, rather than ```question.yaml``` 😄

**Comment by nodobi** [comment]
@yeonns Okay, I'll change `question.yaml` to `config.yml`

**Review by yeonns — APPROVED** [review]
@nodobi Look so nice! 👍 
With your question template, ```euphony-hub-collector``` discussions will be used a lot :)

**Review by designe — APPROVED** [review]
👍 LGTM

**Pull request merged**
